#!/bin/bash

# Released under MIT License

# Copyright (c) 2025 Achille MARTIN

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# ---- GLOBAL VARIABLES ----

# OS Identification
OS_DETECTED="unknown"
OS_DISTRIBUTION_DETECTED="unknown"
OS_DISTRIBUTION_RELEASE_DETECTED="unknown"
OS_DISTRIBUTION_MAJOR_RELEASE_DETECTED="unknown"
OS_ARCHITECTURE_DETECTED="unknown"
OS_PLATFORM_DETECTED="unknown"

# OS support
IS_OS_PLATFORM_SUPPORTED="unknown"
IS_DISTRIBUTION_MAJOR_RELEASE_SUPPORTED="unknown"
# Maintain a list of minimum supported (distribution) major releases
# for the common OS platforms
# Note: the format of the OS platform string
# is based on the default generated by `get_os_platform_string()`
# helper function, and the major release number must only be one integer
declare -A MIN_SUPPORTED_MAJOR_RELEASE_DICT
MIN_SUPPORTED_MAJOR_RELEASE_DICT["linux_ubuntu_x86_64"]="22"

# Config management
DEFAULT_CUSTOM_CONFIG_NAME="nvim-robotics"
DEFAULT_SHORT_ALIAS="neo"
DEFAULT_LOADER_SCRIPT_NAME="nvim_loader.sh"
DEFAULT_INSTALLER_UTILITY_NAME="nvim_installer.sh"

# Version management
NVIM_MIN_STABLE_VERSION="v0.11.0"
NVIM_LATEST_VERSION="unknown"
VIM_PLUG_MIN_STABLE_VERSION="0.14.0"
VIM_PLUG_LATEST_VERSION="unknown"
NVM_MIN_STABLE_VERSION="v0.40.0"
NVM_LATEST_VERSION="unknown"

# Folder structure
DEFAULT_DOWNLOADS_FOLDER="$HOME/Downloads"
DEFAULT_LOCAL_FOLDER="$HOME/.local"
DEFAULT_CONFIG_FOLDER="$HOME/.config"
DEFAULT_BASHRC_PATH="$HOME/.bashrc"
DEFAULT_BASH_ALIASES_PATH="$HOME/.bash_aliases"

# ---- HELPER FUNCTIONS ----

# Highlight a need to source changes
# after environment modifications
source_changes() {
    printf "\n/ ! \\ ACTION REQUIRED: Refresh the state of the environment with the following command\n"
    case "$OS_DETECTED" in
        linux)
            printf "➤ source $DEFAULT_BASHRC_PATH\n"
            ;;
        *)
            printf "✗ Not applicable.\n"
            ;;
    esac
}

# Get the unique string describing the OS platform
get_os_platform_string() {
    local delimiter="_"
    local os_platform_string="${OS_DETECTED}${delimiter}${OS_DISTRIBUTION_DETECTED}${delimiter}${OS_ARCHITECTURE_DETECTED}"
    echo "${os_platform_string}"
}

# Get support status of the (distribution) major release
# for the current OS platform:
# * Returns `0` if release is supported
# * Returns a non-zero exit code (`255`) if release is not supported
# * Returns a non-zero exit code (`1`) if there has been an error during execution
get_support_status_for_distribution_major_release() {
    # Make sure that the minimum supported major release has been registered
    # for the OS platform before proceeding
    if [[ -v MIN_SUPPORTED_MAJOR_RELEASE_DICT["$OS_PLATFORM_DETECTED"] ]];
    then
        # Compare the min supported major release
        # with the current OS distribution major release
        # and return a relevant int code
        local min_supported_distrib_major_release="${MIN_SUPPORTED_MAJOR_RELEASE_DICT["$OS_PLATFORM_DETECTED"]}"
        if [[ "$OS_DISTRIBUTION_MAJOR_RELEASE_DETECTED" -ge "$min_supported_distrib_major_release" ]];
        then
            return 0
        else
            return 255
        fi
    else
        printf "ERROR: the minimum supported major release has not been registered\n"
        printf "for the OS platform: ${OS_PLATFORM_DETECTED}\n"
        return 1
    fi
}

# Check OS specifications to determine support
check_os_specifications() {
    if [[ -n "$OSTYPE" ]];
    then
        if [[ "$OSTYPE" =~ linux|Linux|LINUX ]];
        then
            OS_DETECTED="linux"
            local distribution_detected="$(lsb_release -i)"
            if [[ "$distribution_detected" =~ ubuntu|Ubuntu|UBUNTU ]];
            then
                OS_DISTRIBUTION_DETECTED="ubuntu"
                OS_DISTRIBUTION_RELEASE_DETECTED="$(lsb_release -rs)"
                OS_DISTRIBUTION_MAJOR_RELEASE_DETECTED="$(echo $OS_DISTRIBUTION_RELEASE_DETECTED | cut -d '.' -f 1)"
                local architecture_detected="$(uname -i)"
                if [[ "$architecture_detected" =~ x86_64 ]];
                then
                    OS_ARCHITECTURE_DETECTED="x86_64"

                    # Update the OS platform name
                    IS_OS_PLATFORM_SUPPORTED=1
                    OS_PLATFORM_DETECTED="$(get_os_platform_string)"
                    # Check status support for distribution release
                    local get_release_support_cmd="$(get_support_status_for_distribution_major_release)"
                    local get_release_support_cmd_status="$?"
                    if [[ "$get_release_support_cmd_status" -eq 0 ]];
                    then
                        IS_DISTRIBUTION_MAJOR_RELEASE_SUPPORTED=1
                    elif [[ "$get_release_support_cmd_status" -eq 255 ]];
                    then
                        IS_DISTRIBUTION_MAJOR_RELEASE_SUPPORTED=0
                        printf "WARNING: the OS platform is supported,\n"
                        printf "but the distribution major release \`$OS_DISTRIBUTION_MAJOR_RELEASE_DETECTED\` is not supported.\n"
                        printf "The script will adapt its process for unsupported releases,\n"
                        printf "as much as possible.\n"
                    else
                        printf "$get_release_support_cmd\n"
                        printf "ERROR: The OS platform \`$OS_PLATFORM_DETECTED\`is not registered,\n"
                        printf "therefore assumed to not be supported.\n"
                        exit 1
                    fi
                else
                    printf "ERROR: the architecture \`$architecture_detected\` is not supported.\n"
                    print_usage
                    exit 1
                fi
            else
                printf "ERROR: the distribution \`$distribution_detected\` is not supported.\n"
                print_usage
                exit 1
            fi
        else
            printf "ERROR: the current OS \`$OSTYPE\` is not supported.\n"
            print_usage
            exit 1
        fi
    else
        printf "ERROR: the current OS platform cannot be determined.\n"
        printf "Please verify the supported platforms.\n"
        print_usage
        exit 1
    fi
}

# Search and refresh the latest neovim version available
# accessible via `NVIM_LATEST_VERSION`
refresh_latest_nvim_version() {
    sudo apt-get install curl
    local curl_cmd="$(curl -s "https://api.github.com/repos/neovim/neovim/tags" | grep -o '"v.*"' | head -1 | sed 's/"//g')"
    local curl_cmd_status="$?"
    # Report any curl error to the user
    if [[ "$curl_cmd_status" -ne 0 ]];
    then
        printf "ERROR: Cannot determine the latest neovim version available.\n"
        exit 1
    else
        NVIM_LATEST_VERSION="$curl_cmd"
    fi
}

# Check neovim version to ensure all features are available
# with the config
check_nvim_version() {
    # Get current neovim version
    local current_nvim_version="unknown"
    if [[ $(which nvim) ]];
    then
        current_nvim_version="$(nvim --version | head -1 | grep -o 'v.*$')"
    else
        printf "ERROR: no neovim version has been detected.\n"
        printf "Make sure to install neovim first.\n"
        printf "Please refer to the installer utility: \`$DEFAULT_INSTALLER_UTILITY_NAME\`\n"
        exit 1
    fi

    # Get latest neovim version available
    refresh_latest_nvim_version

    # Compare latest neovim / minimum stable neovim with current neovim
    if [[ "$current_nvim_version" != "$NVIM_LATEST_VERSION" ]];
    then
        printf "WARNING: your are currently using neovim version \`$current_nvim_version\`.\n"
        printf "However, the latest neovim version available is \`$NVIM_LATEST_VERSION\`."
        printf "Therefore, you might not benefit from the latest features available.\n"
        printf "Make sure that you are at least using the minimum stable version of neovim \`$NVIM_MIN_STABLE_VERSION\`\n"
        printf "to get a full-featured config.\n"
    fi
}

# Search and refresh the latest vim-plug version available
# accessible via `VIM_PLUG_LATEST_VERSION`
refresh_vim_plug_version() {
    sudo apt-get install curl
    local curl_cmd="$(curl -s "https://api.github.com/repos/junegunn/vim-plug/tags" | grep -o '".*"' | head -1 | cut -d " " -f 2 | sed 's/"//g')"
    local curl_cmd_status="$?"
    # Report any curl error to the user
    if [[ "$curl_cmd_status" -ne 0 ]];
    then
        printf "ERROR: Cannot determine the latest vim-plug version available.\n"
        exit 1
    else
        VIM_PLUG_LATEST_VERSION="$curl_cmd"
    fi
}

# Search and refresh the latest nvm (Node Version Manager) version available
# accessible via `NVM_LATEST_VERSION`
refresh_latest_nvm_version() {
    sudo apt-get install curl
    local curl_cmd="$(curl -s "https://api.github.com/repos/nvm-sh/nvm/tags" | grep -o '"v.*"' | head -1 | sed 's/"//g')"
    local curl_cmd_status="$?"
    # Report any curl error to the user
    if [[ "$curl_cmd_status" -ne 0 ]];
    then
        printf "ERROR: Cannot determine the latest nvm version available.\n"
        exit 1
    else
        NVM_LATEST_VERSION="$curl_cmd"
    fi
}
