#!/bin/bash

# Released under MIT License

# Copyright (c) 2025 Achille MARTIN

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# ---- HANDY VARIABLES ----

NEOVIM_TAG="latest"
OS_DETECTED="unknown"
OS_DISTRIBUTION_DETECTED="unknown"
OS_DISTRIBUTION_RELEASE_DETECTED="unknown"
OS_DISTRIBUTION_MAJOR_RELEASE_DETECTED="unknown"
OS_ARCHITECTURE_DETECTED="unknown"

DEFAULT_LOCAL_FOLDER="$HOME/.local"

# Maintain a list of minimum supported major releases
# for the common OS platforms
# Note: the format of the OS platform string
# is based on the default generated by `get_os_platform` function
# and the major release number must only be one integer
declare -A MIN_SUPPORTED_MAJOR_RELEASE_DICT
MIN_SUPPORTED_MAJOR_RELEASE_DICT["linux_ubuntu_x86_64"]="22"

# ---- HANDY FUNCTIONS ----

print_usage() {
    multiline_usage_txt="
    Usage: bash $(basename "$0") CMD

    Purpose: Manage the installation and uninstallation of neovim
             on various OS platforms
             (supported platforms: Linux Ubuntu x86_64)

    CMD:
        install             Install latest neovim version
                            for the current OS platform
                            Note: automatically installs
                            the unsupported release of neovim if necessary

        uninstall           Remove all neovim versions from current OS platform

        --help, -h          Show this help
    "

    printf "%s" "$multiline_usage_txt"
}

source_changes() {
    printf "\n / ! \\ ACTION: Refresh the state of the environment with the following command\n"
    case "$OS_DETECTED" in
        linux)
            local bashrc_path="$HOME/.bashrc"
            printf "source $bashrc_path\n"
            ;;
        *)
            printf "Not applicable.\n"
            ;;
    esac
}

check_os_type() {
    # Check OS specifications to determine support
    if [[ -n "$OSTYPE" ]];
    then
        if [[ "$OSTYPE" =~ linux|Linux|LINUX ]];
        then
            OS_DETECTED="linux"
            distribution_detected="$(lsb_release -i)"
            if [[ "$distribution_detected" =~ ubuntu|Ubuntu|UBUNTU ]];
            then
                OS_DISTRIBUTION_DETECTED="ubuntu"
                OS_DISTRIBUTION_RELEASE_DETECTED="$(lsb_release -rs)"
                OS_DISTRIBUTION_MAJOR_RELEASE_DETECTED="$(echo $OS_DISTRIBUTION_RELEASE_DETECTED | cut -d '.' -f 1)"
                architecture_detected="$(uname -i)"
                if [[ "$architecture_detected" =~ x86_64 ]];
                then
                    OS_ARCHITECTURE_DETECTED="x86_64"
                else
                    printf "ERROR: the architecture \`$architecture_detected\` is not supported.\n"
                    print_usage
                    exit 1
                fi
            else
                printf "ERROR: the distribution \`$distribution_detected\` is not supported.\n"
                print_usage
                exit 1
            fi
        else
            printf "ERROR: the current OS \`$OSTYPE\` is not supported.\n"
            print_usage
            exit 1
        fi
    else
        printf "ERROR: the current OS platform cannot be determined.\n"
        printf "Please verify the supported platforms.\n"
        print_usage
        exit 1
    fi
}

# Function to get the full OS platform string
get_os_platform() {
    delimiter="_"
    os_platform_string="${OS_DETECTED}${delimiter}${OS_DISTRIBUTION_DETECTED}${delimiter}${OS_ARCHITECTURE_DETECTED}"
    echo "${os_platform_string}"
}

# Function to check whether the major release
# for the current OS platform is supported or not
# Returns 0 if OS platform is supported (equivalent to true)
# otherwise returns a non-zero exit code (255) if OS platform is not supported (equivalent to false)
# or returns a non-zero exit code (1) if there has been an error during execution (equivalent to error)
check_supported_major_release() {
    os_platform_detected="$(get_os_platform)"
    # Make sure that the minimum supported major release has been registered
    # for the OS platform before proceeding
    if [[ -v MIN_SUPPORTED_MAJOR_RELEASE_DICT["$os_platform_detected"] ]];
    then
        # Compare the release numbers
        min_supported_os_major_release="${MIN_SUPPORTED_MAJOR_RELEASE_DICT["$os_platform_detected"]}"
        if [[ "$OS_DISTRIBUTION_MAJOR_RELEASE_DETECTED" -ge "$min_supported_os_major_release" ]];
        then
            return 0
        else
            return 255
        fi
    else
        printf "ERROR: the minimum supported major release has not been registered\n"
        printf "for the OS platform: ${os_platform_detected}\n"
        return 1
    fi
}

perform_install() {
    # Handle the different OS platforms supported
    case "$OS_DETECTED" in

        linux)
            printf "\nEnsuring that there is no neovim version clash...\n"
            if [[ $(which nvim) ]];
            then
                printf "ERROR: a neovim version has been detected.\n"
                printf "Make sure to remove existing versions of neovim before installation\n"
                printf "to avoid clashes.\n"
                print_usage
                exit 1
            fi
            printf "...done\n"

            # Download and install the latest neovim version
            printf "\nMoving to the downloads folder...\n"
            local downloads_folder="$HOME/Downloads"
            if [[ ! -d "$downloads_folder"  ]];
            then
                mkdir -p "$downloads_folder"
            fi
            cd $downloads_folder
            printf "...done\n"

            case "$OS_DISTRIBUTION_DETECTED" in

                ubuntu)
                    printf "\nInstalling necessary dependencies...\n"
                    sudo apt-get install curl
                    printf "...done\n"

                    case "$OS_ARCHITECTURE_DETECTED" in

                        x86_64)
                            printf "\nDownloading neovim archive...\n"
                            # Adapt the download method
                            # depending on major release support
                            func_cmd="$(check_supported_major_release)"
                            func_cmd_status="$?"
                            if [[ "$func_cmd_status" -eq 0 ]];
                            then
                                # If major release is supported
                                curl_cmd="$(curl -LO "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz")"
                            elif [[ "$func_cmd_status" -eq 255 ]];
                            then
                                # If major release is not supported
                                curl_cmd="$(curl -LO "https://github.com/neovim/neovim-releases/releases/latest/download/nvim-linux-x86_64.tar.gz")"
                            else
                                # If there has been an error
                                # while trying to determine the state
                                # of the major release
                                printf "$func_cmd\n"
                                printf "Not downloading any archive. Please review the log messages.\n"
                                exit 1
                            fi
                            curl_cmd_status="$?"
                            # Report any curl error to the user
                            if [[ "$curl_cmd_status" -ne 0 ]];
                            then
                                printf "ERROR: Cannot download the neovim archive. Please review the log messages.\n"
                                exit 1
                            fi
                            printf "...done\n"

                            printf "\nInstalling neovim in the add-on software location...\n"
                            sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
                            sudo mv /opt/nvim-linux-x86_64 /opt/nvim
                            printf "...done\n"

                            printf "\nAdding neovim path to bashrc (if not there already)...\n"
                            local bashrc_path="$HOME/.bashrc"
                            local bashrc_content=$(sed '' "$bashrc_path")
                            local source_neovim_cmd_txt='export PATH="$PATH:/opt/nvim/bin"'
                            if [[ ! "$bashrc_content" =~ "$source_neovim_cmd_txt" ]];
                            then
                                printf "# Make neovim visible\n" >> "$bashrc_path"
                                printf 'export PATH="$PATH:/opt/nvim/bin"' >> "$bashrc_path"
                                printf "\n" >> "$bashrc_path"
                            fi
                            printf "...done\n"
                            ;;

                        *)
                            printf "ERROR: the current OS architecture \`$OS_ARCHITECTURE_DETECTED\` is not supported.\n"
                            print_usage
                            exit 1
                            ;;

                    esac
                    ;;

                *)
                    printf "ERROR: the distribution \`$OS_DISTRIBUTION_DETECTED\` is not supported.\n"
                    print_usage
                    exit 1
                    ;;

            esac
            ;;

        *)
            printf "ERROR: the current OS \`$OS_DETECTED\` is not supported.\n"
            print_usage
            exit 1
            ;;

    esac
    # Highlight post-action requests to the user
    source_changes
}

perform_uninstall() {
    case "$OS_DETECTED" in

        linux)
            # Remove application added from downloaded package
            printf "Removing application installed from downloaded package...\n"
            sudo rm -rf /opt/nvim*
            printf "...done\n"

   			# Remove user data related to neovim
            printf "Removing user data related to neovim from local folder \`$DEFAULT_LOCAL_FOLDER\`...\n"
            sudo rm -rf "$DEFAULT_LOCAL_FOLDER/share/nvim"
            printf "...done\n"

            case "$OS_DISTRIBUTION_DETECTED" in

                ubuntu)
                    # Remove application installed from apt
                    printf "\nRemoving application installed from apt...\n"
                    sudo apt-get remove neovim
                    printf "...done\n"
                    ;;

                *)
                    printf "ERROR: the distribution \`$OS_DISTRIBUTION_DETECTED\` is not supported.\n"
                    print_usage
                    exit 1
                    ;;

            esac
            ;;


        *)
            printf "ERROR: the current OS \`$OS_DETECTED\` is not supported.\n"
            print_usage
            exit 1
            ;;

    esac

    # Highlight post-action requests to the user
    source_changes
}

# ---- MAIN ----

# Ensure that the OS platform is supported
check_os_type

# Ensure that there is at least one required argument entered
if [[ "$#" -lt 1 ]]
then
    printf "ERROR: one argument required\n"
	print_usage
	exit 1
fi

# Perform action depending on command entered
case "$1" in
    --help|-h)
        print_usage
	    exit 1
        ;;

    install)
        perform_install
        ;;

    uninstall)
        perform_uninstall
        ;;

    *)
        printf "ERROR: first argument not valid\n"
        print_usage
        exit 1
        ;;
esac
