# Optional identifier for the workflow
# that appears in the Github Actions tab
name: check_platform_compability

# Events that trigger the workflow
on:
  # Triggers the workflow on push to the "main" branch
  push:
    branches:
      - "main"
  # Triggers the workflow on specific actions tied to a pull request
  # For instance, when a pull request is opened
  # or when a commit is pushed, or when the PR is ready for review
  pull_request:
  # Triggers the workflow when manually commanded from the Actions tab
  workflow_dispatch:

# Set default settings for the workflow
defaults:
  run:
    # Use bash as default shell
    # and force interactive mode
    # to make use of ~/.bashrc
    # Also, use extra options for error handling
    shell: bash -ieo pipefail {0}

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # Job aimed at building the code
  build:
    # The type of runner that the job runs on
    runs-on: ubuntu-22.04
    # Sequence of tasks executed as part of the job
    steps:
      # Ensure that the OS/distribution is updated
      - name: Ensure OS updated
        run: sudo apt-get update -y && sudo apt-get upgrade -y
      # Check out the repository under $GITHUB_WORKSPACE
      # so that the job can access it
      - name: Checkout code
        uses: actions/checkout@v4
      # Ensure that the scripts are executable
      # to enable full inter-operability
      - name: Make scripts executable
        run: chmod +x "./scripts/helper_functions.sh" &&
             chmod +x "./scripts/nvim_installer.sh" &&
             chmod +x "./scripts/nvim_config_manager.sh"
      # Install Neovim via the dedicated bash script
      - name: Install Neovim
        run: ./scripts/nvim_installer.sh install && source ~/.bashrc
      # Check Neovim installation by printing out the version
      - name: Check Neovim installation
        run: nvim --version
      # Set up the default configuration
      # TODO: retrieve current branch
      - name: Set up default repo configuration
        run: ./scripts/nvim_config_manager.sh quick-setup
      # Check repo configuration aliases
      - name: Check Neovim aliases
        run: nvim-robotics --version && neo --version
